### ISSUE TITLE
Comparing shapes with those from CFHTLS pipeline

### ISSUE THREAD

**Issue by mssgill** [DarkEnergyScienceCollaboration/CFHTLS-Reprocess#2]

**Comment by rmandelb** [comment]
I hope you all don't mind comments from the peanut gallery.  Just wanted to point out that if you're not using the same shear estimation method, you don't expect to get the same per-galaxy shapes (for many reasons).  So you could compare inferred shears for massive objects, e.g., stacked tangential shears for a bunch of clusters, but comparing per-object shears is unlikely to be helpful.

Sorry if that's what you already had in mind - it just didn't seem like it from the title of the issue.

**Comment by boutigny** [comment]
Thanks for mentioning this @rmandelb this is worth reminding it, at least to me.

**Comment by cwwalter** [comment]
Thanks Rachel.  @boutigny What relevant entries for each object are actually in the CFHT catalog?  Is there also a ellipticity that might have an exact analog in the stack that we can use just for comparison purposes.  For example the SDSS shape algorithm is implemented there.  Or is Rachel's point that even that will be different?

**Comment by rmandelb** [comment]
Yes, that will be different.

**Comment by mssgill** [comment]
@cwwalter -  Not sure this will answer your q, but in my experience, unless it is exactly the same pipeline, it will yield a different per galaxy ellipticity, as @rmandelb says, sometimes _highly_ different, but with the mean being the same, so only statistically avg'ing over many galaxies will it agree (in e.g. a correlation function, or doing cluster profiles).  [Thx for chiming in, @rmandelb .]

**Comment by cwwalter** [comment]
OK, I understand.  Thanks.  I would naively think that the photometry would be shape independent, is this effect mostly driven by ISR?

**Comment by mssgill** [comment]
@cwwalter - i think the photometry will likely be much more similar, whatever pipeline is used to measure it, since it's pre-WL shape measurement, and "all" one has to do is gather all the photons in the affected pixels (after ISR = instrument signal removal -- i.e. part of image processing -- as opposed to initial state radiation, which is what you and i know it as in our 'previous lives').  But for shapes, there are complicated interactions with removal of the PSF that will result in different final shapes for each object.

Corrections welcome if i've misstated anything here..

(And thx to bus seatmate Josh M. for discussions on this).
