### ISSUE TITLE
Quantify performance of measurement algorithm between DM and CFHT pipeline

### ISSUE THREAD

**Issue by cwwalter** [DarkEnergyScienceCollaboration/CFHTLS-Reprocess#3]
We want to determine how well the DM pipeline performs relative to the previous survey work.  

Some ideas include comparing detection efficiency of objects as a function of magnitude compared to the truth information in overlapping Hubble fields.

**Comment by boutigny** [comment]
Here is a picture of the whiteboard mocking up a possible result plot comparing the performance of algorithms.

![20150206_112415](https://cloud.githubusercontent.com/assets/5713323/6086511/5426aeaa-adf7-11e4-88df-460bec14f97f.jpg)

**Comment by cwwalter** [comment]
We need to find the matching Hubble field.

The most appropriate comparison seems to be CFHT Deep field 2 with HST [COSMOS](http://cosmos.astro.caltech.edu/astronomer/hst.html).  The COSMOS field goes to magnitude 27.5 and many other surveys have pointed at the same area.

**Comment by mmmerlin** [comment]
I think the COSMOS data can be downloaded from here:

http://irsa.ipac.caltech.edu/Missions/cosmos.html
and : http://archive.stsci.edu/prepds/cosmos/acsdatalist.html

**Comment by mmmerlin** [comment]
Regarding taking HST data as "truth" with respect to PSF, this page mentions that the PSF changes wrt time in a complex fashion due to thermal expansion/contraction of the telescope during orbit, and presents a model/prediction of the effect:

http://www.astro.caltech.edu/~rjm/acs/PSF/

**Comment by rmandelb** [comment]
For what it's worth, in the COSMOS data that is packaged in a way that GalSim can use it, we have per-object PSF estimates that include the above model.  Can you re-use our stuff?

**Comment by boutigny** [comment]
I suppose that the COSMOS data packaged for GalSim are available here : https://www.dropbox.com/sh/ns2yh4q00trqs5r/JypUX8qwLw

**Comment by rmandelb** [comment]
No, that's actually for GalSim v0.5 or less.  For the newer version, you should follow the instructions labeled (2) on https://github.com/GalSim-developers/GalSim/wiki/RealGalaxy%20Data and follow the link to the GREAT3 page where the data live.
